### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by maccaspacca** [maccaspacca/BismuthToolsWeb#14]
^C^XERROR:tornado.application:Uncaught exception Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/tornado/http1connection.py", line 237, in _read_message delegate.finish() File "/usr/local/lib/python3.6/dist-packages/tornado/httpserver.py", line 230, in finish self.request_callback(self.request) File "/usr/local/lib/python3.6/dist-packages/tornado/wsgi.py", line 276, in call WSGIContainer.environ(request), start_response) File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in call return self.wsgi_app(environ, start_response) File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/Bismuth/BismuthToolsWeb/bismuthtoolsweb.py", line 1808, in handler x = getcirc() File "/home/Bismuth/BismuthToolsWeb/bismuthtoolsweb.py", line 746, in getcirc c.execute("SELECT sum(reward) FROM transactions;")

**Comment by maccaspacca** [comment]
Investigating

**Comment by maccaspacca** [comment]
This looks like a tornado application fault. For some reason tornado was unable to process the request and the program froze. As the process ran normally until this point (and has since) I suspect a resource issue server side. Perhaps the connection to the database or node was lost or there was a memory / cpu issue on the server host. I have monitored resource usage on the test node and found no evidence of memory leaks, cpu issues etc. so I can only conclude this is a rare occurence.

**Comment by maccaspacca** [comment]
I will move the circulation figure into a global variable and check every five minutes. This will reduce the number of requests to the node.
