### ISSUE TITLE
local variable 'db_block_height' referenced before assignment

### ISSUE THREAD

**Issue by kenneth** [maccaspacca/BismuthToolsWeb#15]
```
 ✗ python3 bismuthtoolsweb.py
Logging level: WARNING (30)
bismuthtoolsweb.py:47: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(open(r'toolsconfig.ini'))
Bismuth DB path = ~/Bismuth/static/ledger.db
Bismuth DB root = ~/Bismuth/static/
Hyper.db exists = False
Hyper.db path = ~/Bismuth/static/ledger.db
No connection
Traceback (most recent call last):
  File "bismuthtoolsweb.py", line 799, in <module>
    latest()
  File "bismuthtoolsweb.py", line 336, in latest
    app_log.info("Latest block queried: {}".format(str(db_block_height)))
UnboundLocalError: local variable 'db_block_height' referenced before assignment
```

**Comment by maccaspacca** [comment]
That error is generated when there is no connection to the Bismuth node. The proceedure queries the node api for the latest block using a network socks connection. This has failed for some reason hence the "No connection" statement before the traceback. Please make sure you have a successful connection to a working Bismuth node. Please make sure the IP of the node is placed into toolsconfig.ini and there is nothing preventing a network connection (firewall etc.)
