### ISSUE TITLE
Tools Hangs

### ISSUE THREAD

**Issue by Adorid** [maccaspacca/BismuthToolsWeb#3]
With lot of requests tools hangs, probably bottle problem

**Comment by Adorid** [comment]
^C----------------------------------------
Exception happened during processing of request from ('84.164.206.27', 44686)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 119, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt

**Comment by hclivess** [comment]
I have had issues with Bottle too, unfortunately. Alternatives are Flask, Django, Pyramid, haven't tested either of them

**Comment by maccaspacca** [comment]
I will explore use of alternatives that are more robust.

**Comment by maccaspacca** [comment]
I am testing conversion to flask as per main bismuth web resources

**Comment by maccaspacca** [comment]
Flask conversion complete. Now in production at bismuth.online

**Comment by maccaspacca** [comment]
No more instances since move over to flask
