### ISSUE TITLE
Web Tools fail when querying coinmarketcap stats api

### ISSUE THREAD

**Issue by maccaspacca** [maccaspacca/BismuthToolsWeb#5]
raise value

 File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request

   rv = self.dispatch_request()

 File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request

   return self.view_functions[rule.endpoint](**req.view_args)

 File "/home/coins/Bismuth/BismuthToolsWeb/bismuthtoolsweb.py", line 800, in home

   cmcstats = get_cmc_info(cust_curr)

 File "/home/coins/Bismuth/BismuthToolsWeb/bismuthtoolsweb.py", line 95, in get_cmc_info

   y = json.loads(x)

 File "/usr/lib/python3.5/json/__init__.py", line 319, in loads

   return _default_decoder.decode(s)

 File "/usr/lib/python3.5/json/decoder.py", line 339, in decode

   obj, end = self.raw_decode(s, idx=_w(s, 0).end())

 File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode

   raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2018-01-25 19:41:07,866] ERROR in app: Exception on /richest [GET]

Traceback (most recent call last):

 File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app

   response = self.full_dispatch_request()

 File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request

   rv = self.handle_user_exception(e)

 File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception

   reraise(exc_type, exc_value, tb)

 File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise

   raise value

 File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request

   rv = self.dispatch_request()

 File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request

   return self.view_functions[rule.endpoint](**req.view_args)

 File "/home/coins/Bismuth/BismuthToolsWeb/bismuthtoolsweb.py", line 1143, in richest_form

   conv_curr = get_cmc_val(def_curr)

 File "/home/coins/Bismuth/BismuthToolsWeb/bismuthtoolsweb.py", line 115, in get_cmc_val

   y = json.loads(x)

 File "/usr/lib/python3.5/json/__init__.py", line 319, in loads

   return _default_decoder.decode(s)

 File "/usr/lib/python3.5/json/decoder.py", line 339, in decode

   obj, end = self.raw_decode(s, idx=_w(s, 0).end())

 File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode

   raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by maccaspacca** [comment]
CMC stats are queried on the fly when a user accesses or updates a page. It appears that CMC has limits and potentially blocks sites requesting too often.

**Comment by maccaspacca** [comment]
QF001012018 proposal

Update code to query CMC separately and within the limits described by the site i.e. every five minutes.

**Comment by maccaspacca** [comment]
Code now in test
